//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.PessoaFisicas = new HashSet<PessoaFisica>();
            this.PessoaJuridicas = new HashSet<PessoaJuridica>();
            this.Vendas = new HashSet<Venda>();
        }
    
        public int Id { get; set; }
        public string Endereco { get; set; }
        public string CEP { get; set; }
        public string Cidade { get; set; }
        public string UF { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
        public string Obs { get; set; }
        public string TipoPessoa { get; set; }
        public string Bairro { get; set; }
    
        public virtual ICollection<PessoaFisica> PessoaFisicas { get; set; }
        public virtual ICollection<PessoaJuridica> PessoaJuridicas { get; set; }
        public virtual ICollection<Venda> Vendas { get; set; }
    }
}
