//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataSource
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjetoFinalEntities : DbContext
    {
        public ProjetoFinalEntities()
            : base("name=ProjetoFinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Usuario> Usuarios { get; set; }
        public DbSet<Cliente> Clientes { get; set; }
        public DbSet<PessoaFisica> PessoaFisicas { get; set; }
        public DbSet<PessoaJuridica> PessoaJuridicas { get; set; }
        public DbSet<Entrega> Entregas { get; set; }
        public DbSet<Venda> Vendas { get; set; }
        public DbSet<Devolucao> Devolucaos { get; set; }
        public DbSet<ItemDevolucao> ItemDevolucaos { get; set; }
        public DbSet<ItemPedido> ItemPedidoes { get; set; }
        public DbSet<Produto> Produtos { get; set; }
    }
}
