//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemDevolucao
    {
        public int Quantidade { get; set; }
        public int IdProduto { get; set; }
        public int IdDevolucao { get; set; }
    
        public virtual Devolucao Devolucao { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
