//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPedido
    {
        public ItemPedido()
        {
            this.Devolucaos = new HashSet<Devolucao>();
        }
    
        public int Id { get; set; }
        public int Quantidade { get; set; }
        public int IdProduto { get; set; }
        public int IdVenda { get; set; }
        public bool Entrega { get; set; }
    
        public virtual ICollection<Devolucao> Devolucaos { get; set; }
        public virtual Venda Venda { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
