//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public Produto()
        {
            this.ItemDevolucaos = new HashSet<ItemDevolucao>();
            this.ItemPedidoes = new HashSet<ItemPedido>();
        }
    
        public int Id { get; set; }
        public string Descricao { get; set; }
        public double PrecoCompra { get; set; }
        public double PrecoVenda { get; set; }
        public double MargemLucro { get; set; }
        public string Localizacao { get; set; }
        public string Marca { get; set; }
        public int SaldoAtual { get; set; }
        public bool Situacao { get; set; }
    
        public virtual ICollection<ItemDevolucao> ItemDevolucaos { get; set; }
        public virtual ICollection<ItemPedido> ItemPedidoes { get; set; }
    }
}
